### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por ID
GET http://localhost:3000/movies/feb6cc38-7304-11f0-82df-c0185032fd70

### Recuperar peliculas por Genero
GET http://localhost:3000/movies?genre=Drama

### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Gigantes de Acero 2026",
    "year": 2026,
    "director": "Federico Redolfo",
    "duration": 163,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
        "Drama",
        "Adventure",
        "Sci-Fi" 
    ],
    "rate": 9.8
}

### Actualizar una pelicula
PATCH http://localhost:3000/movies/feb6cc38-7304-11f0-82df-c0185032fd70
Content-Type: application/json

{
    "year": 2013
}

### Eliminar una pelicula
DELETE http://localhost:3000/movies/feb6c51c-7304-11f0-82df-c0185032fd70