### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por ID
GET http://localhost:3000/movies/68896baf89228fa81248f553

### Recuperar peliculas por Genero
GET http://localhost:3000/movies?genre=Drama

### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Nueva tarea",
    "year": 2026,
    "director": "Federico Redolfo",
    "duration": 163,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
        "Drama",
        "Adventure",
        "Sci-Fi" 
    ],
    "rate": 9.8
}

### Actualizar una pelicula
PATCH http://localhost:3000/movies/2e8f3f27-1968-4c89-a5cc-17b9597603df
Content-Type: application/json

{
    "year": 2026
}

### Eliminar una pelicula
DELETE http://localhost:3000/movies/52637348-0d81-48b4-a8a9-3685eecafba7